#!/usr/bin/env python3
"""Validate a frozen Phase 11 logits-only oracle artifact."""

import argparse
import hashlib
import json
from pathlib import Path


def token_hash(token_ids):
    payload = json.dumps(token_ids, separators=(",", ":"), ensure_ascii=True).encode("ascii")
    return hashlib.sha256(payload).hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate Phase 11 logits-only oracle")
    parser.add_argument("--corpus", required=True, help="token_ids.json generated by make_phase11_corpus.py")
    parser.add_argument("--manifest", required=True, help="oracle manifest.json")
    parser.add_argument("--minimum", type=int, default=4096)
    args = parser.parse_args()

    corpus_path = Path(args.corpus)
    manifest_path = Path(args.manifest)
    corpus = json.loads(corpus_path.read_text(encoding="utf-8"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    token_ids = corpus.get("token_ids")
    if not isinstance(token_ids, list) or len(token_ids) < args.minimum:
        raise SystemExit(f"corpus has fewer than {args.minimum} token IDs")
    expected_hash = corpus.get("token_ids_sha256")
    actual_hash = token_hash([int(x) for x in token_ids])
    if expected_hash != actual_hash:
        raise SystemExit(
            f"corpus token hash mismatch: metadata={expected_hash!r} actual={actual_hash}"
        )

    positions = manifest.get("positions")
    if not isinstance(positions, list) or len(positions) < args.minimum:
        raise SystemExit(f"manifest has fewer than {args.minimum} positions")
    if len(positions) != len(token_ids):
        raise SystemExit(
            f"manifest/corpus length mismatch: {len(positions)} != {len(token_ids)}"
        )

    total_bytes = 0
    for index, record in enumerate(positions):
        if int(record.get("position", -1)) != index:
            raise SystemExit(f"manifest position {index} is not contiguous")
        if int(record.get("token_id", -1)) != int(token_ids[index]):
            raise SystemExit(
                f"token mismatch at position {index}: "
                f"manifest={record.get('token_id')} corpus={token_ids[index]}"
            )

        tensors = record.get("tensors")
        if not isinstance(tensors, list):
            raise SystemExit(f"position {index} tensors must be an array")
        logits = [t for t in tensors if t.get("name") == "logits"]
        if len(logits) != 1:
            raise SystemExit(f"position {index} must contain exactly one logits tensor")
        tensor = logits[0]
        if tensor.get("dtype") != "FP32":
            raise SystemExit(f"position {index} logits are not FP32")
        shape = tensor.get("shape")
        if not isinstance(shape, list) or len(shape) != 1 or int(shape[0]) <= 0:
            raise SystemExit(f"position {index} logits shape is invalid: {shape!r}")

        expected_bytes = int(shape[0]) * 4
        if int(tensor.get("bytes", expected_bytes)) != expected_bytes:
            raise SystemExit(f"position {index} logits byte metadata is invalid")
        logits_path = manifest_path.parent / str(tensor.get("file", ""))
        if not logits_path.is_file():
            raise SystemExit(f"missing logits file at position {index}: {logits_path}")
        actual_bytes = logits_path.stat().st_size
        if actual_bytes != expected_bytes:
            raise SystemExit(
                f"position {index} logits size mismatch: {actual_bytes} != {expected_bytes}"
            )
        total_bytes += actual_bytes

    oracle_meta = manifest.get("oracle", {})
    kind = oracle_meta.get("kind")
    if kind and kind != "qwen3_8_flash_next_cpu_fp32_logits_only":
        raise SystemExit(f"unexpected oracle kind: {kind!r}")
    if oracle_meta.get("teacher_forced") is False:
        raise SystemExit("oracle metadata says teacher_forced=false")

    print(f"Validated {len(positions)} contiguous Phase 11 FP32 logits positions")
    print(f"token_ids_sha256={actual_hash}")
    print(f"logits_bytes={total_bytes}")


if __name__ == "__main__":
    main()
